version: '2'

services:
  ftp:
    image: noxtech/anonymous-pure-ftp
    container_name: anonymous-ftp
    environment:
      - FTP_PASSIVE_PORTS=40000:40039
    ports:
      - "21:21"
      - "40000-40039:40000-40039"
    volumes:
      - "/srv/store/docker-volumes/ftp/data/anonymous:/home/ftp/"
      - "/srv/store/docker-volumes/ftp/data/ftpusers:/home/ftpusers/"
      - "/srv/store/docker-volumes/ftp/passwd:/etc/pure-ftpd/passwd"
    restart: unless-stopped
